name: bullxchange
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: 4.2.0
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0

  # HTTP and environment
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0

  # Security & PIN
  flutter_secure_storage: ^9.2.2
  pinput: ^5.0.0
  local_auth: ^3.0.0
  crypto: ^3.0.3
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  http: ^1.5.0
  app_links: ^6.3.2
  fl_chart: ^1.1.1
  flutter_svg: ^2.2.1
  auto_size_text: ^3.0.0
  path_provider: ^2.1.5
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/images/splashBottom.png
    - assets/icon/
    - assets/BullXchange Design-PNG/
    - assets/OpenAPIScripMaster.json

  fonts:
    - family: EudoxusSans
      fonts:
        - asset: assets/fonts/EudoxusSans-Regular.ttf
        - asset: assets/fonts/EudoxusSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/EudoxusSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/EudoxusSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/EudoxusSans-Light.ttf
          weight: 300
        - asset: assets/fonts/EudoxusSans-ExtraLight.ttf
          weight: 200

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
