import 'package:cloud_firestore/cloud_firestore.dart';

class TransactionModel {
  final String? id; // Unique transaction ID, generated by Firestore
  final String userId;
  final String symbol;
  final String companyName;
  final String transactionType; // 'BUY' or 'SELL'
  final int quantity;
  final double price; // Price per share
  final double charges;
  final double totalAmount;
  final String orderStatus; // e.g., 'EXECUTED'
  final DateTime executedAt;

  // --- THESE ARE THE REQUIRED FIELDS ---
  final String exchange;
  final String productType;

  TransactionModel({
    this.id,
    required this.userId,
    required this.symbol,
    required this.companyName,
    required this.transactionType,
    required this.quantity,
    required this.price,
    required this.charges,
    required this.totalAmount,
    this.orderStatus = 'EXECUTED', // Defaulting to EXECUTED for this app
    required this.executedAt,

    // --- ADD THESE TO YOUR CONSTRUCTOR ---
    required this.exchange,
    required this.productType,
  });

  /// Converts the model to a Map for Firestore.
  Map<String, dynamic> toJson() {
    return {
      'userId': userId,
      'symbol': symbol,
      'companyName': companyName,
      'transactionType': transactionType,
      'quantity': quantity,
      'price': price,
      'charges': charges,
      'totalAmount': totalAmount,
      'orderStatus': orderStatus,
      'executedAt': Timestamp.fromDate(executedAt),

      // --- ADD THESE TO THE JSON ---
      'exchange': exchange,
      'productType': productType,
    };
  }

  /// Creates a TransactionModel from a Firestore document snapshot.
  factory TransactionModel.fromSnapshot(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;

    return TransactionModel(
      id: doc.id,
      userId: data['userId'],
      symbol: data['symbol'],
      companyName: data['companyName'],
      transactionType: data['transactionType'],
      quantity: data['quantity'],
      price: (data['price'] as num).toDouble(),
      charges: (data['charges'] as num).toDouble(),
      totalAmount: (data['totalAmount'] as num).toDouble(),
      orderStatus: data['orderStatus'],
      executedAt: (data['executedAt'] as Timestamp).toDate(),

      // --- ADD THESE FOR READING FROM FIRESTORE ---
      exchange: data['exchange'] ?? 'NSE', // Default to NSE if missing
      productType: data['productType'] ?? 'Delivery', // Default
    );
  }
}
