import 'package:cloud_firestore/cloud_firestore.dart';

class TransactionModel {
  final String? id; // Unique transaction ID, generated by Firestore
  final String userId;
  final String symbol;
  final String companyName;
  final String transactionType; // 'BUY' or 'SELL'
  final int quantity;
  final double price; // Price per share
  final double charges;
  final double totalAmount;
  final String orderStatus; // e.g., 'EXECUTED'
  final DateTime executedAt;

  TransactionModel({
    this.id,
    required this.userId,
    required this.symbol,
    required this.companyName,
    required this.transactionType,
    required this.quantity,
    required this.price,
    required this.charges,
    required this.totalAmount,
    this.orderStatus = 'EXECUTED', // Defaulting to EXECUTED for this app
    required this.executedAt,
  });

  /// Converts the model to a Map for Firestore.
  Map<String, dynamic> toJson() {
    return {
      'userId': userId,
      'symbol': symbol,
      'companyName': companyName,
      'transactionType': transactionType,
      'quantity': quantity,
      'price': price,
      'charges': charges,
      'totalAmount': totalAmount,
      'orderStatus': orderStatus,
      'executedAt': Timestamp.fromDate(executedAt),
    };
  }
}
