// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMY8CUluTWXwb9hmNAb9gn9HRgDuyY2B4',
    appId: '1:966889537689:web:e73cb90869bcbed169b808',
    messagingSenderId: '966889537689',
    projectId: 'bullxchange-94945',
    authDomain: 'bullxchange-94945.firebaseapp.com',
    storageBucket: 'bullxchange-94945.firebasestorage.app',
    measurementId: 'G-V5G6WR2RRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfA_E0gfZP1d2W7UQ99yd38BwwGtY-tC4',
    appId: '1:966889537689:android:24f07b228b26de4669b808',
    messagingSenderId: '966889537689',
    projectId: 'bullxchange-94945',
    storageBucket: 'bullxchange-94945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEPaLsc17F-S2mk3q3HNI1T1H93qmxgWQ',
    appId: '1:966889537689:ios:42bb16340a6e3cf969b808',
    messagingSenderId: '966889537689',
    projectId: 'bullxchange-94945',
    storageBucket: 'bullxchange-94945.firebasestorage.app',
    iosBundleId: 'com.example.bullxchange',
  );

}